#!/bin/bash

##############################################################################
#
# Muestra un menú con contraseñas de pass en tofi.
#
# Marcos Mikolta
#
##############################################################################

notify() {
	notify-send -u low "Éxito" "Copiado al portapapeles" -i "$1"
}

notify_error() {
	notify-send -u critical "Error" "No se encuentra la información" -i $NOTIFY_ICONS/triangle-exclamation-solid.svg
}

# Muestra todas las claves en $PASSWORD_STORE_DIR
selec=$(find "$PASSWORD_STORE_DIR/" -type f -name '*.gpg' -exec basename {} .gpg \; | tofi --prompt-text="pass: ")
[ -z $selec ] && exit 0

# Logra el enlace al archivo seleccionado
path=$(find "$PASSWORD_STORE_DIR/" -type f -name "$selec.gpg" | grep -oP "^$PASSWORD_STORE_DIR/\K.*(?=\.gpg$)")

if [[ $selec =~ otp ]]; then 
	pass otp -c $path && notify "Código copiado al portapapeles" 
	exit 0
else
	selected=$(printf "Usuario\nClave" | tofi --prompt-text="pass: ")
	case $selected in
		"Usuario")
			pass -c2 $path && notify $NOTIFY_ICONS/user-solid.svg || notify_error ;;
		"Clave")
			pass -c1 $path && notify $NOTIFY_ICONS/key-solid.svg || notify_error ;;
		*)
			exit 0 ;;
	esac
fi
