#!/bin/bash

##############################################################################
#
# Muestra un menú para seleccionar el fondo de pantalla.
#
# Marcos Mikolta
#
##############################################################################

BGFOLDER="$XDG_DATA_HOME"/backgrounds/
BGFILE="$XDG_DATA_HOME"/backgrounds/bg-setup.sh

ILABEL="Selector de fondo de pantalla"

# Comprobar que existe la carpeta como el archivo.
[[ -d "$BGFOLDER" ]] || mkdir "$BGFOLDER"
[[ -f "$BGFILE" ]] || touch "$BGFILE"

cd "$BGFOLDER"
IMG_PATH="$(fzfcha "$ILABEL")"

[[ -z "$IMG_PATH" ]] && exit 0

printf 'swaybg -m fill -i "%s"\n' "$IMG_PATH" > "$BGFILE"
