#!/bin/bash

##############################################################################
#
# Muestra un menú con imágenes usando fzf.
#
# Marcos Mikolta
#
##############################################################################

# Script que muestra las imágenes en el menú de fzf
# y devuelve la ruta completa del archivo.

IMG=$(ls *.png *.jpg *.jpeg *.webp 2>/dev/null | fzf --style=full --reverse --input-label "$1" --preview-label "$2" --preview 'chafa --size=${FZF_PREVIEW_COLUMNS}x${FZF_PREVIEW_LINES} {}')

[[ -z "$IMG" ]] && exit 0

echo $(pwd)/"$IMG"
