#!/bin/bash

##############################################################################
#
# Muestra un menú para seleccionar el fondo de pantalla.
#
# Marcos Mikolta
#
##############################################################################

BGFOLDER="$XDG_DATA_HOME"/backgrounds/
BGFILE="$HOME"/.local/scripts/bg-setup

ILABEL="Selector de fondo de pantalla"

# Comprobar que existe la carpeta como el archivo.
[[ -d "$BGFOLDER" && -f "$BGFILE" ]] || exit 1

cd "$BGFOLDER"
IMG_PATH="$(fzfcha "$ILABEL")"

[[ -z "$IMG_PATH" ]] && exit 0

printf 'swaybg -m fill -i "%s"\n' "$IMG_PATH" > "$BGFILE"
