#!/bin/bash

##############################################################################
#
# Atajos para buscar en paginas web o busquedas generales.
#
# Marcos Mikolta
#
##############################################################################

order="$(printf "" | tofi --require-match=false --prompt-text='Buscar en Internet: ')"
[ -z "$order" ] && exit 0

word="$(printf "$order" | sed 's/^[^ ]* //')"

case "$order" in
	yt\ *)
		search_url="https://www.youtube.com/results?search_query=";;
	pdb\ *)
		search_url="https://www.protondb.com/search?q=";;
	rae\ *)
		search_url="https://dle.rae.es/?m=form&w=";;
	*)
		search_url="https://duckduckgo.com/?t=h_&q="
		word="$order";;
esac

# Separa $BROWSER en diferentes arrays
IFS=' ' read -r -a browser_cmd <<< "$BROWSER"
"${browser_cmd[@]}" "${search_url}${word}"	
