#!/bin/bash

##############################################################################
#
# Diversas maneras para capturar la pantalla.
#
# Marcos Mikolta
#
##############################################################################

notify() {
	notify-send -u low "Captura realizada" -i $NOTIFY_ICONS/image-solid.svg
}

[ -d "$GRIM_DEFAULT_DIR" ] || mkdir -p $GRIM_DEFAULT_DIR

case $1 in
	"-f") # Capturar la pantalla entera
		grim && notify ;;
	"-s") # Capturar zona seleccionada
		grim -g "$(slurp -w 0)" &&	notify ;;
	"-w") # Capturar ventana enfocada
		grim -g "$(swaymsg -t get_tree | jq -r '.. | select(.focused? and .pid?) | "\(.rect.x + .window_rect.x),\(.rect.y + .window_rect.y) \(.window_rect.width)x\(.window_rect.height)"')" && notify ;;
	*)
		printf "Instrucciones de uso:\ncpant -f --> Captura completa de pantalla\ncpant -s --> Captura zona seleccionada\ncpant -w --> Captura ventana enfocada" ;;
esac

exit

