#!/bin/bash

##############################################################################
#
# Fondo de bloqueo de pantalla de bloqueo el mismo que en Sway.
#
# Marcos Mikolta
#
##############################################################################

wallpaper=$(cat ~/.config/sway/config.d/background.conf | awk '{print $4}')
swaylock -i $wallpaper -f --indicator-idle-visible --indicator-radius 75 --font FiraSans
