#!/bin/bash

##############################################################################
#
# Fondo de pantalla de bloqueo el mismo que el escritorio.
#
# Marcos Mikolta
#
##############################################################################

BGFILE="$XDG_DATA_HOME"/backgrounds/bg-setup.sh

wallpaper=$(sed -n 's/.*"\([^"]*\)".*/\1/p' "$BGFILE")
swaylock -i "$wallpaper" -f --indicator-idle-visible --indicator-radius 75 --font FiraSans
