#!/bin/bash

##############################################################################
#
# Fondo de pantalla de bloqueo el mismo que el escritorio.
#
# Marcos Mikolta
#
##############################################################################

FILE="$HOME/.local/scripts/bg-setup"

wallpaper=$(sed -n 's/.*"\([^"]*\)".*/\1/p' "$FILE")
swaylock -i "$wallpaper" -f --indicator-idle-visible --indicator-radius 75 --font FiraSans
