#!/bin/bash

##############################################################################
#
# Muestra un menú con diferentes opciones para el sistema.
#
# Marcos Mikolta
#
##############################################################################

selected="$(printf "Bloquear\nCerrar sesión\nSuspender\nReiniciar\nApagar" | tofi --prompt-text='Sesión de mi PC: ')"

case $selected in
	"Bloquear")
		super-swaylock;;
	"Cerrar"*)
		swaymsg exit;;
	"Suspender")
		super-swaylock & systemctl suspend;;
	"Reiniciar")
		systemctl reboot;;
	"Apagar")
		systemctl poweroff;;
	*)
		exit 0;;
esac

